######################## default configuration ####################
baseURL = "http://demo.gethugothemes.com/bigspring-light/examplesite/"
title = "Brainstorm Security Ltd - Social Engineering and Penetration testing"
theme = "bigspring-light"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-7MV278ZN07" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
