#################### default parameters ################################
logo = "images/logo.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Brainstorm Security"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "https://formsubmit.co/0d626e80fc1b8a591a9117591c115597" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Need a negotiator?"
link = "ransomware-negotiation"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/brainstormsec"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://www.twitter.com/Brainstorm_Sec"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/brainstormsecurity"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/brainstorm-security"

[[social]]
title = "youtube"
icon = "fab fa-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCutknd5G5x9_OpbpCyd7m6w"
